<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\DB;

class MataKuliahSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'id_matakuliah' => (string) Str::uuid(),
                'kode_matakuliah' => '23STNKN1121',
                'nama_matakuliah' => 'Bahasa Indonesia',
                'sks' => 2,
                'semester' => 1,
                'group' => '15A',
                'hari' => 'Senin',
                'jam' => '15:30-18:00',
                'kapasitas' => 40,
                'peserta' => 38,
            ],
            [
                'id_matakuliah' => (string) Str::uuid(),
                'kode_matakuliah' => '23STNKN1124',
                'nama_matakuliah' => 'Pancasila',
                'sks' => 2,
                'semester' => 1,
                'group' => '15A',
                'hari' => 'Selasa',
                'jam' => '07:00-09:30',
                'kapasitas' => 40,
                'peserta' => 38,
            ],
            [
                'id_matakuliah' => (string) Str::uuid(),
                'kode_matakuliah' => '23STNKN1125',
                'nama_matakuliah' => 'Kriptografi',
                'sks' => 3,
                'semester' => 1,
                'group' => '15A',
                'hari' => 'Selasa',
                'jam' => '09:30-12:00',
                'kapasitas' => 40,
                'peserta' => 20,
            ],
            [
                'id_matakuliah' => (string) Str::uuid(),
                'kode_matakuliah' => '23STNKN1126',
                'nama_matakuliah' => 'Web Programming',
                'sks' => 3,
                'semester' => 3,
                'group' => '35A',
                'hari' => 'Kamis',
                'jam' => '09:30-12:00',
                'kapasitas' => 40,
                'peserta' => 38,
            ],
            [
                'id_matakuliah' => (string) Str::uuid(),
                'kode_matakuliah' => '23STNKN1127',
                'nama_matakuliah' => 'Mobile Programming',
                'sks' => 3,
                'semester' => 3,
                'group' => '35A',
                'hari' => 'Kamis',
                'jam' => '07:00-09:30',
                'kapasitas' => 40,
                'peserta' => 36,
            ],
            [
                'id_matakuliah' => (string) Str::uuid(),
                'kode_matakuliah' => '23STNKN1128',
                'nama_matakuliah' => 'Algoritma Pemrograman',
                'sks' => 3,
                'semester' => 3,
                'group' => '35A',
                'hari' => 'Jumat',
                'jam' => '13:30-15:40',
                'kapasitas' => 40,
                'peserta' => 38,
            ],
            // Semester 1 tambahan
            [
                'id_matakuliah' => (string) Str::uuid(),
                'kode_matakuliah' => '23STNKN1129',
                'nama_matakuliah' => 'Matematika Dasar',
                'sks' => 3,
                'semester' => 1,
                'group' => '15A',
                'hari' => 'Rabu',
                'jam' => '13:00-15:30',
                'kapasitas' => 40,
                'peserta' => 35,
            ],
            [
                'id_matakuliah' => (string) Str::uuid(),
                'kode_matakuliah' => '23STNKN1130',
                'nama_matakuliah' => 'Pengantar Teknologi Informasi',
                'sks' => 2,
                'semester' => 1,
                'group' => '15A',
                'hari' => 'Kamis',
                'jam' => '07:00-09:30',
                'kapasitas' => 40,
                'peserta' => 40,
            ],
            [
                'id_matakuliah' => (string) Str::uuid(),
                'kode_matakuliah' => '23STNKN1131',
                'nama_matakuliah' => 'Logika Informatika',
                'sks' => 3,
                'semester' => 1,
                'group' => '15A',
                'hari' => 'Jumat',
                'jam' => '09:30-12:00',
                'kapasitas' => 40,
                'peserta' => 37,
            ],
            // Semester 2
            [
                'id_matakuliah' => (string) Str::uuid(),
                'kode_matakuliah' => '23STNKN1201',
                'nama_matakuliah' => 'Struktur Data',
                'sks' => 4,
                'semester' => 2,
                'group' => '25A',
                'hari' => 'Senin',
                'jam' => '07:00-10:30',
                'kapasitas' => 40,
                'peserta' => 32,
            ],
            [
                'id_matakuliah' => (string) Str::uuid(),
                'kode_matakuliah' => '23STNKN1202',
                'nama_matakuliah' => 'Basis Data',
                'sks' => 3,
                'semester' => 2,
                'group' => '25A',
                'hari' => 'Selasa',
                'jam' => '13:00-15:30',
                'kapasitas' => 40,
                'peserta' => 38,
            ],
            [
                'id_matakuliah' => (string) Str::uuid(),
                'kode_matakuliah' => '23STNKN1203',
                'nama_matakuliah' => 'Pemrograman Web Dasar',
                'sks' => 3,
                'semester' => 2,
                'group' => '25A',
                'hari' => 'Rabu',
                'jam' => '07:00-09:30',
                'kapasitas' => 40,
                'peserta' => 35,
            ],
            [
                'id_matakuliah' => (string) Str::uuid(),
                'kode_matakuliah' => '23STNKN1204',
                'nama_matakuliah' => 'Jaringan Komputer',
                'sks' => 3,
                'semester' => 2,
                'group' => '25A',
                'hari' => 'Kamis',
                'jam' => '13:00-15:30',
                'kapasitas' => 40,
                'peserta' => 30,
            ],
            [
                'id_matakuliah' => (string) Str::uuid(),
                'kode_matakuliah' => '23STNKN1205',
                'nama_matakuliah' => 'Sistem Operasi',
                'sks' => 3,
                'semester' => 2,
                'group' => '25A',
                'hari' => 'Jumat',
                'jam' => '07:00-09:30',
                'kapasitas' => 40,
                'peserta' => 33,
            ],
            // Semester 3 tambahan
            [
                'id_matakuliah' => (string) Str::uuid(),
                'kode_matakuliah' => '23STNKN1301',
                'nama_matakuliah' => 'Pemrograman Berorientasi Objek',
                'sks' => 4,
                'semester' => 3,
                'group' => '35A',
                'hari' => 'Senin',
                'jam' => '13:00-16:30',
                'kapasitas' => 40,
                'peserta' => 36,
            ],
            [
                'id_matakuliah' => (string) Str::uuid(),
                'kode_matakuliah' => '23STNKN1302',
                'nama_matakuliah' => 'Analisis dan Perancangan Sistem',
                'sks' => 3,
                'semester' => 3,
                'group' => '35A',
                'hari' => 'Rabu',
                'jam' => '13:00-15:30',
                'kapasitas' => 40,
                'peserta' => 34,
            ],
            [
                'id_matakuliah' => (string) Str::uuid(),
                'kode_matakuliah' => '23STNKN1303',
                'nama_matakuliah' => 'Interaksi Manusia Komputer',
                'sks' => 2,
                'semester' => 3,
                'group' => '35A',
                'hari' => 'Sabtu',
                'jam' => '07:00-09:30',
                'kapasitas' => 40,
                'peserta' => 28,
            ],
            // Semester 4
            [
                'id_matakuliah' => (string) Str::uuid(),
                'kode_matakuliah' => '23STNKN1401',
                'nama_matakuliah' => 'Web Framework',
                'sks' => 3,
                'semester' => 4,
                'group' => '45A',
                'hari' => 'Selasa',
                'jam' => '07:00-09:30',
                'kapasitas' => 40,
                'peserta' => 25,
            ],
            [
                'id_matakuliah' => (string) Str::uuid(),
                'kode_matakuliah' => '23STNKN1402',
                'nama_matakuliah' => 'Rekayasa Perangkat Lunak',
                'sks' => 4,
                'semester' => 4,
                'group' => '45A',
                'hari' => 'Rabu',
                'jam' => '07:00-10:30',
                'kapasitas' => 40,
                'peserta' => 30,
            ],
            [
                'id_matakuliah' => (string) Str::uuid(),
                'kode_matakuliah' => '23STNKN1403',
                'nama_matakuliah' => 'Keamanan Informasi',
                'sks' => 3,
                'semester' => 4,
                'group' => '45A',
                'hari' => 'Kamis',
                'jam' => '13:00-15:30',
                'kapasitas' => 40,
                'peserta' => 27,
            ],
            [
                'id_matakuliah' => (string) Str::uuid(),
                'kode_matakuliah' => '23STNKN1404',
                'nama_matakuliah' => 'Machine Learning',
                'sks' => 3,
                'semester' => 4,
                'group' => '45A',
                'hari' => 'Jumat',
                'jam' => '13:00-15:30',
                'kapasitas' => 40,
                'peserta' => 22,
            ],
            [
                'id_matakuliah' => (string) Str::uuid(),
                'kode_matakuliah' => '23STNKN1405',
                'nama_matakuliah' => 'Manajemen Proyek TI',
                'sks' => 2,
                'semester' => 4,
                'group' => '45A',
                'hari' => 'Sabtu',
                'jam' => '09:30-12:00',
                'kapasitas' => 40,
                'peserta' => 28,
            ],
        ];

        foreach ($data as $mk) {
            DB::table('mata_kuliah')->insert($mk);
        }
    }
}
